### ISSUE TITLE
Research: Physische Netzwerke aktivieren und konfigurieren; jeder node muss 2 Netzwerke haben?

### ISSUE THREAD

**Issue by Mieneas** [verteilte-systeme-projekt/OurSky#9]
Bitte fasse die Egebnisse des Researches zusammen und lade diese in GitHub hoch in Research/sprint1 directory

**Comment by vogeljo-tu** [comment]
https://github.com/verteilte-systeme-projekt/OurSky/blob/master/Research/Sprint-1/Netzwerke.md
